config/routes.rb
Blog::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :uploads

  root :to => 'welcome#index'

  get "welcome/index"

  devise_for :users

end

app/models/upload.rb
	class Upload < ActiveRecord::Base
	attr_accessible :name, :photo, :document, :audio, :video

	has_attached_file :photo, :styles => { :small => "150x150>" },
	              :url  => "/assets/uploads/:id/:style/:basename.:extension",
	              :path => ":rails_root/public/assets/uploads/:id/:style/:basename.:extension"

	# validates_attachment_presence :photo
	validates_attachment_size :photo, :less_than => 5.megabytes
	validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']



	has_attached_file :document, styles: {thumbnail: "60x60#"}
	validates_attachment :document, content_type: { content_type: "application/pdf" }


	has_attached_file :audio
	validates_attachment_content_type :audio, :content_type => [ 'audio/mp3','audio/mpeg'],
                     :file_name => { :matches => [/mp3\Z/] }

	has_attached_file :video
	validates_attachment_content_type :video, :content_type => [ 'video/mp4', 'video.mov', 'video/mpeg','video/mpeg4','video/x-flv',
		'video/x-matroska','video/webm','video/avi','video/ogg','video/x-divx','video/divx','video/x-msvideo', 'video/quicktime', 
		'video/3gpp', 'video/x-ms-wmv', 'flv-application/octet-stream', 'video/mpeg4', 'video/x-la-asf', 'video/x-ms-asf', 
		'video/msvideo', 'video/avi', '"video/x-msvideo', 'video/x-ms-wmv']
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_filter :set_upload, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @uploads = Upload.all
    respond_with(@uploads)
  end

  def show
    respond_with(@upload)
  end

  def new
    @upload = Upload.new
    respond_with(@upload)
  end

  def edit
  end

  def create
    @upload = Upload.new(params[:upload])
    @upload.save
    respond_with(@upload)
  end

  def update
    @upload.update_attributes(params[:upload])
    respond_with(@upload)
  end

  def destroy
    @upload.destroy
    respond_with(@upload)
  end

  private
    def set_upload
      @upload = Upload.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_filter :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="/assets/favicon-white-blue.png">

    <title>DEMO BLOG</title>

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    
    <!-- Bootstrap CSS -->    
    <link href="/assets/bootstrap.min.css" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="/assets/bootstrap-theme.css" rel="stylesheet">
    <!--external css-->
   
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
 
      <!-- Custom styles -->
      <link href="/assets/style.css" rel="stylesheet">
      <link href="/assets/style-responsive.css" rel="stylesheet" />
      <link href="/assets/jquery-ui-1.10.4.min.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 -->
    <!--[if lt IE 9]>
      <script src="/assets/html5shiv.js"></script>
      <script src="/assets/respond.min.js"></script>
      <script src="/assets/lte-ie7.js"></script>
    <![endif]-->
  </head>

  <body>
    <section id="container" class="">

    <% if user_signed_in? %>
    <!-- container section start -->
          <header class="header dark-bg">
            <div class="toggle-nav">
                <div class="" data-original-title="Toggle Navigation" data-placement="bottom"></div>
            </div>

            <!--logo start-->
            <a href="/" class="logo">DEMO<span class="lite"> BLOG</span></a>
            <!--logo end-->

            <div class="nav search-row" id="top_menu">
                <!--  search form start -->
                <ul class="nav top-menu">                    
                    <li>
                        
                    </li>                    
                </ul>
                <!--  search form end -->                
            </div>

              

              <div class="top-nav notification-row">                
                <!-- notificatoin dropdown start-->
                <ul class="nav pull-right top-menu">
                    <!-- user login dropdown start-->
                    <% if user_signed_in? %>
                      <li class="dropdown">
                          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                              <span class="profile-ava">
                                  <img src="/assets/avatar-mini4.jpg">
                              </span>&nbsp;
                              <span class="username"> <%= current_user.email %></span>
                              <b class="caret"></b>
                          </a>
                          <ul class="dropdown-menu extended logout">
                              <div class="log-arrow-up"></div>
                              <li class="eborder-top">
                                  <%= link_to '<i class="fa fa-user fa-white"></i> Profile'.html_safe, edit_user_registration_path %>
                              </li>
                              <li>
                                <%= link_to '<i class="fa fa-sign-out fa-white"></i> Sign Out'.html_safe, destroy_user_session_path, :method => :delete %>
                              </li>
                          </ul>
                      </li>
                    <% else %>
                       <li><%= link_to "Sign up", new_user_registration_path %></li>
                      <li><%= link_to "Sign in", new_user_session_path %></li>
                    <% end %>
                    <!-- user login dropdown end -->
                </ul>
             </div>
        </header>      
        <!--header end-->

        <!--sidebar start-->
      <aside>
          <div id="sidebar"  class="nav-collapse ">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu">                
                  <li class="active">
                      <a class="" href="/">
                          <i class="fa fa-home"></i>
                          <span>Dashboard</span>
                      </a>
                  </li>
                  <li class="sub-menu">
                      <a href="/uploads" class="">
                          <i class="fa  fa-file-pdf-o"></i>
                          <span>PDF Upload</span>
                       </a>
                  </li>
                  <li class="sub-menu">
                      <a href="/uploads" class="">
                          <i class="fa fa-file-image-o"></i>
                          <span>IMAGE Upload</span>
                       </a>
                  </li>
                  <li class="sub-menu">
                      <a href="/uploads" class="">
                          <i class="fa fa-file-audio-o"></i>
                          <span>AUDIO Upload</span>
                       </a>
                  </li>
                  <li class="sub-menu">
                      <a href="/uploads" class="">
                          <i class="fa  fa-file-video-o"></i>
                          <span>VIDEO Upload</span>
                       </a>
                  </li>

                  
              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>
      <!--sidebar end-->
      
    <% end %>

    
    <!--main content start-->
      <section id="main-content">
          <section class="wrapper"> 

          <%= yield %>
          </section>
      </section>
      <!--main content end-->
     </section>

 <!-- javascripts -->
    <script src="/assets/jquery.js"></script>
    <script src="/assets/jquery-ui-1.10.4.min.js"></script>
    <script src="/assets/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="/assets/jquery-ui-1.9.2.custom.min.js"></script>
    <!-- bootstrap -->
    <script src="/assets/bootstrap.min.js"></script>
    <!-- nice scroll -->
    <script src="/assets/jquery.scrollTo.min.js"></script>
    <script src="/assets/jquery.nicescroll.js" type="text/javascript"></script>

    <script src="/assets/bootstrap.min.js"></script>
    <!-- nice scroll -->
  
    
  <script src="/assets/audio.min.js"></script>
  <script>
  audiojs.events.ready(function() {
    var as = audiojs.createAll();
  });
</script>

  </body>
</html>

app/views/uploads/_form.html.erb
<%= form_for(@upload) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :document %><br />
    <%= f.file_field :document %>
  </div>
  <div class="field">
    <%= f.label :audio %><br />
    <%= f.file_field :audio %>
  </div>
  <div class="field">
    <%= f.label :video %><br />
    <%= f.file_field :video %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<h1>Listing uploads</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Photo</th>
    <th>Document</th>
    <th>Video</th>
    <th>Audio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @uploads.each do |upload| %>
  <tr>
    <td><%= upload.name %></td>
    <td><%= image_tag upload.photo, :size => "150x150" %></td>
    <td><%= upload.document_file_name %></td>
    <td><%= upload.video_file_name %></td>
    <td><%= upload.audio_file_name %></td>
    <td><%= link_to 'Show', upload %></td>
    <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
    <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Upload', new_upload_path %>

app/views/uploads/new.html.erb
<h1>New upload</h1>

<%= render 'form' %>

<%= link_to 'Back', uploads_path %>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @upload.name %>
</p>
<p>
  <b>Photo:</b>
  <%= image_tag @upload.photo, :size => "150x150" %>
</p>



<p>
  <b>Document:</b>
  <p><%= @upload.document_file_name %></p>
  <a href="<%= @upload.document %>" target="_blank"><img src="http://aglou.caminosurf.com/images/icons/pdf_icon_x64.png"></a>
</p>

<p>
  <b>Video:</b>
  <p><%= @upload.video_file_name %></p>
             <!--  <%= video_tag @upload.video, controls: true, type: "video/mp4" %>

              <iframe width="490" height="275" src="<%= video_path @upload.video %>" frameborder="0" allowfullscreen autoplay="true">
            </iframe> -->
<video width="320" height="240" controls>
  <source src='<%= @upload.video %>' />
</video>

</p>


<p>
  <b>Audio:</b>
  <p><%= @upload.audio_file_name %></p>
  <audio src="<%= @upload.audio %>" preload="none" />
</p>


<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>